### ISSUE TITLE
Doesn't stop when click pause button in a list. 

### ISSUE THREAD

**Issue by serzhan181** [serzhan181/Meere#1]
When you click pause button (not one on the bottom) it doesn't stop the music.

**Comment by Khusyasy** [comment]
Hi, can I have more info on this issue?

**Comment by serzhan181** [comment]
@Khusyasy
Yeah. When you choose a music and play it - the player on the bottom with controllers appears. It works correctly when you click pause/play. But in the list itself there's also pause/play button, so when you click on that, it doesn't stop the music. 

The problem here is that you gotta initialize first click. If user clicked on that music the first time - it plays the music, if that music is already playing - you pause that, etc.

**Comment by Khusyasy** [comment]
Hey I think have fixed the issue, can please check it out, thanks!.
